## Atividades da aulda sobre Numpy

Importando biblioteca


In [3]:
import numpy as np

Gerar ndarray de 2 x 3 e litas com 3 elementos cada

In [6]:
dados=np.random.rand(2,3)

In [7]:
dados

array([[0.58378432, 0.88826931, 0.69999694],
       [0.02967102, 0.34132954, 0.48061548]])

Tipo de dados

In [8]:
dados.dtype

dtype('float64')

Tamanho e dimensões

In [9]:
dados.shape

(2, 3)

In [10]:
dados.ndim

2

Criar ndarray usando a função array

In [11]:
lista=[1,2,5,7.8,1.25]

In [12]:
dados2=np.array(lista)

In [13]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

In [16]:
lista2=[[1,2,3,4],[4,3,2,1]]

In [17]:
dados3=np.array(lista2)

In [18]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

Outras maneiras de criar arrays

In [19]:
dadoszero=np.zeros(10)

In [20]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
dadoszero2=np.zeros((2,3))

In [22]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
dadosum=np.ones(5)

In [24]:
dadosum

array([1., 1., 1., 1., 1.])

In [25]:
dadosseq=np.arange(10)

In [26]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
dadosseq2=np.arange(0,20,2)

In [28]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
dadosseq.dtype

dtype('int64')

In [35]:
dadosseqf=dadosseq.astype(np.float64)

In [37]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [38]:
dadosseqf.dtype

dtype('float64')

Aritmética com array

In [39]:
dados4=np.array([[1,2,3],[4,5,6]])

In [40]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

In [42]:
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

In [43]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [44]:
dados5=dados4+dados4

In [45]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [46]:
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

In [47]:
dados>dados5

array([[False, False, False],
       [False, False, False]])

Indexação

In [48]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
dadosseq[5]

5

In [50]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
dadosseq[3:6]

array([3, 4, 5])

In [52]:
dadosseq[3:6]=20

In [53]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [54]:
fatiados=dadosseq[2:4]

In [55]:
fatiados

array([ 2, 20])

In [56]:
fatiados[1]=2000

In [58]:
fatiados

array([   2, 2000])

In [59]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

In [61]:
fatiados[:]=333

In [62]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

Copiar dados

In [64]:
fatia2=dadosseq[2:4].copy()

In [65]:
fatia2

array([333, 333])

In [66]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

Array com mais de uma dimensão

In [67]:
dados6=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [68]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
dados6[1,2]

6

Máscaras

In [70]:
mascara=(dadosseq<100)

In [71]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

In [72]:
dadosseq[dadosseq<20]=8888

In [73]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888])

Transposição

In [74]:
dados7=np.arange(15).reshape((3,5))

In [75]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [77]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

Multiplicação de Matrizes com dot

In [78]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])